import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import type { LLMAdapter } from "../../llm/src/core/adapter";
import type { LLMRequest, LLMResponse } from "../../llm/src/core/types";
import type { LlmProvider } from "../../llm/src/config.js";
import type { LlmModelCatalog, LlmModelDescriptor } from "../../llm/src/model-catalog";
import {
    createSlashCommandRegistry,
    modelCommandDefinition,
    type ModelCommandEffect,
} from "../../slash-command/src/index.js";
import {
    createCompositionRoot,
    createDefaultToolPolicy,
} from "../src/cli";
import type { UiViewModel } from "../src/types";

const CANARY_SECRET = "sk-live-canary-test-token-sec8848-xyz";

class SensitiveFakeAdapter implements LLMAdapter {
    readonly provider = "openai";
    readonly structuredOutputMode = "strict" as const;
    readonly calls: LLMRequest[] = [];
    /** 模拟 Adapter 内部持有的敏感凭证，严禁泄漏到任何快照、轨迹、Trace 或 ViewModel 中。 */
    readonly apiKey: string = CANARY_SECRET;

    constructor(
        public modelId: string = "model-alpha",
        private readonly responseGenerator?: (callIndex: number) => LLMResponse,
    ) {}

    async generate(request: LLMRequest): Promise<LLMResponse> {
        this.calls.push(request);
        if (this.responseGenerator) {
            return this.responseGenerator(this.calls.length - 1);
        }
        return {
            content: JSON.stringify({
                result: {
                    kind: "ask_user",
                    questions: [
                        {
                            header: "Clarification",
                            question: `Question generated by ${this.modelId}`,
                            options: [
                                { label: "Option 1", description: null },
                                { label: "Option 2", description: null },
                            ],
                            multiSelect: false,
                        },
                    ],
                    memoryPatch: null,
                },
            }),
        };
    }
}

class FakeCatalog implements LlmModelCatalog {
    constructor(private readonly models: readonly LlmModelDescriptor[]) {}

    async list(): Promise<readonly LlmModelDescriptor[]> {
        return this.models;
    }
}

function createDescriptor(
    id: string,
    displayName: string,
    provider: LlmProvider = "openai",
    selectable = true,
): LlmModelDescriptor {
    return {
        id,
        displayName,
        provider,
        selectable,
        availabilitySource: "live",
        metadataSource: "catalog",
        contextWindowTokens: 128_000,
        maxOutputTokens: 4096,
    };
}

async function setupE2eWorkspace(): Promise<{ workspace: string; cleanup: () => Promise<void> }> {
    const workspace = await mkdtemp(join(tmpdir(), "lazygoal-e2e-canary-"));
    return {
        workspace,
        cleanup: async () => {
            await rm(workspace, { recursive: true, force: true });
        },
    };
}

/** 递归扫描目录下所有文件的文本内容，用于断言无任何 canary 敏感字符串泄漏。 */
async function scanDirectoryForSecret(dir: string, secret: string): Promise<string[]> {
    const leakPaths: string[] = [];
    async function walk(currentDir: string): Promise<void> {
        let entries;
        try {
            entries = await readdir(currentDir, { withFileTypes: true });
        } catch {
            return;
        }
        for (const entry of entries) {
            const full = join(currentDir, entry.name);
            if (entry.isDirectory()) {
                await walk(full);
            } else if (entry.isFile()) {
                const text = await readFile(full, "utf8");
                if (text.includes(secret)) {
                    leakPaths.push(full);
                }
            }
        }
    }
    await walk(dir);
    return leakPaths;
}

test("端到端组合流：// 转义入会话、/model 命令被拦截不入会话、模型切换后后续推进使用新模型", async () => {
    const { workspace, cleanup } = await setupE2eWorkspace();
    try {
        const adapterMap = new Map<string, SensitiveFakeAdapter>();
        const catalogModels = [
            createDescriptor("model-alpha", "Model Alpha (Default)"),
            createDescriptor("model-beta", "Model Beta (Upgraded)"),
        ];

        const initialAdapter = new SensitiveFakeAdapter("model-alpha");
        adapterMap.set("model-alpha", initialAdapter);

        // 真实实例化 Composition Root，不 mock 持久化，所有文件写入 workspace 对应的 Home。
        const root = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: initialAdapter,
            modelCatalog: new FakeCatalog(catalogModels),
            adapterFactory: (sel) => {
                let adp = adapterMap.get(sel.modelId);
                if (!adp) {
                    adp = new SensitiveFakeAdapter(sel.modelId);
                    adapterMap.set(sel.modelId, adp);
                }
                return adp;
            },
            profile: {
                id: "default",
                systemPrompt: "You are an AI assistant.",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        const capturedViewModels: UiViewModel[] = [];
        root.controller.subscribe(() => {
            capturedViewModels.push(root.controller.getSnapshot());
        });

        // 1. 初始化 SlashCommandRegistry，模拟文本输入框组件的行为
        const registry = createSlashCommandRegistry<ModelCommandEffect>();
        registry.register(modelCommandDefinition);

        // 2. 测试 // 转义输入提交
        const escapedInput = "//Create a service with /model in name";
        const dispatchResult1 = await registry.dispatch(escapedInput);
        assert.equal(dispatchResult1.kind, "escaped_text");
        assert.equal(dispatchResult1.content, "/Create a service with /model in name");

        // 派发转义后的文本作为 intent 创建 Goal
        await root.controller.dispatch({
            kind: "create",
            intent: dispatchResult1.content,
        });

        const sessionView1 = root.controller.getSnapshot();
        assert.equal(sessionView1.screen, "session");
        assert.equal(sessionView1.waitingFor, "ask_user");

        // 验证 Goal messages 与状态包含转义后的普通文本
        assert.ok(sessionView1.goal.state.messages.length > 0);
        assert.equal(
            sessionView1.goal.state.messages[0]?.content,
            "/Create a service with /model in name",
        );
        // 第一轮执行使用的是 model-alpha
        assert.equal(initialAdapter.calls.length, 1);

        // 3. 在会话等待点模拟输入 /model
        const slashInput = "/model";
        const dispatchResult2 = await registry.dispatch(slashInput);
        assert.equal(dispatchResult2.kind, "executed");
        assert.equal(dispatchResult2.effect.kind, "open_model_selector");

        // 派发 openModelSelector 命令
        await root.controller.dispatch({ kind: "openModelSelector" });

        // 验证进入 model_select 屏幕
        const selectView = root.controller.getSnapshot();
        assert.equal(selectView.screen, "model_select");

        // 关键断言：/model 命令文本绝不能进入 Goal 的任何 messages 中！
        for (const msg of selectView.goal?.state.messages ?? []) {
            assert.notEqual(msg.content, "/model");
        }

        // 4. 选择新模型 model-beta
        await root.controller.dispatch({
            kind: "selectModel",
            model: catalogModels[1]!,
        });

        // 切换后回到 session 屏幕，并展示切换 notice
        const sessionView2 = root.controller.getSnapshot();
        assert.equal(sessionView2.screen, "session");
        assert.equal(sessionView2.notice?.kind, "info");
        assert.match(sessionView2.notice?.message ?? "", /Model switched to Model Beta \(Upgraded\)/);
        assert.equal(sessionView2.goal.state.modelSelection?.modelId, "model-beta");
        assert.equal(root.modelBinding.current().selection.modelId, "model-beta");

        // 5. 提交后续回答，推进执行
        assert.ok(sessionView2.askUser !== undefined);
        await root.controller.dispatch({
            kind: "answerAskUser",
            requestId: sessionView2.askUser.requestId,
            answers: [
                {
                    questionId: sessionView2.askUser.questions[0]!.id,
                    optionIds: [sessionView2.askUser.questions[0]!.options[0]!.id],
                },
            ],
        });

        // 切换后的新请求必须路由到 model-beta 对应的 Adapter
        const betaAdapter = adapterMap.get("model-beta");
        assert.ok(betaAdapter !== undefined);
        assert.ok(betaAdapter.calls.length >= 1);

        // 验证 notice 在下一次交互推进后被自动清除
        const sessionView3 = root.controller.getSnapshot();
        assert.equal(sessionView3.screen, "session");
        if (sessionView3.screen === "session") {
            assert.equal(sessionView3.notice, undefined);
        }

        // 验证旧 adapter 在切换后未收到新的模型调用
        assert.equal(initialAdapter.calls.length, 1);
    } finally {
        await cleanup();
    }
});

test("敏感凭据（Canary Secret）隔离审计：持久化快照、轨迹、Trace 日志、ViewModel 树均无任何泄漏", async () => {
    const { workspace, cleanup } = await setupE2eWorkspace();
    try {
        const catalogModels = [
            createDescriptor("model-alpha", "Model Alpha"),
            createDescriptor("model-beta", "Model Beta"),
        ];
        const initialAdapter = new SensitiveFakeAdapter("model-alpha");

        const root = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: initialAdapter,
            modelCatalog: new FakeCatalog(catalogModels),
            adapterFactory: (sel) => new SensitiveFakeAdapter(sel.modelId),
            profile: {
                id: "default",
                systemPrompt: "System prompt",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        const capturedStates: UiViewModel[] = [];
        root.controller.subscribe(() => {
            capturedStates.push(JSON.parse(JSON.stringify(root.controller.getSnapshot())));
        });

        // 创建并推进 Goal
        await root.controller.dispatch({
            kind: "create",
            intent: "Perform canary audit task",
        });

        // 切换模型
        await root.controller.dispatch({ kind: "openModelSelector" });
        await root.controller.dispatch({
            kind: "selectModel",
            model: catalogModels[1]!,
        });

        // 再次推进
        await root.controller.dispatch({
            kind: "submitMessage",
            content: "Step 2 message",
        });

        // 1. 扫描当前测试 Home 下的所有文件（包括 goals 快照、trajectories 轨迹、traces 诊断日志）
        const lazygoalDir = join(workspace, "lazygoal-home");
        const leakedFiles = await scanDirectoryForSecret(lazygoalDir, CANARY_SECRET);
        assert.deepEqual(
            leakedFiles,
            [],
            `敏感凭证 ${CANARY_SECRET} 泄漏到了以下文件中：${leakedFiles.join(", ")}`,
        );

        // 2. 检查内存中发射过的所有 ViewModel 状态树
        const viewModelsJson = JSON.stringify(capturedStates);
        assert.equal(
            viewModelsJson.includes(CANARY_SECRET),
            false,
            "敏感凭据泄漏到了 UiViewModel 状态中！",
        );

        // 3. 检查持久化快照反序列化对象的 modelSelection 仅包含安全公开元数据
        const savedGoalId = root.controller.getSnapshot().screen === "session"
            ? (root.controller.getSnapshot() as any).goal.id
            : "";
        const savedGoal = await root.store.restore(savedGoalId);
        assert.ok(savedGoal !== undefined);
        const sel = savedGoal.state.modelSelection;
        assert.ok(sel !== undefined);
        assert.equal((sel as any).apiKey, undefined);
        assert.equal((sel as any).secret, undefined);
        assert.equal((sel as any).authorization, undefined);
    } finally {
        await cleanup();
    }
});

test("跨进程会话恢复：Provider 兼容时重建 Binding，不兼容时拒绝静默推进并停在选择错误态", async () => {
    const { workspace, cleanup } = await setupE2eWorkspace();
    try {
        const catalogModels = [
            createDescriptor("model-initial", "Model Initial", "openai"),
            createDescriptor("model-custom", "Model Custom", "openai"),
        ];
        const initialAdapter = new SensitiveFakeAdapter("model-initial");

        // 1. 在第一个会话中创建 Goal 并切换到 model-custom
        const root1 = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: initialAdapter,
            modelCatalog: new FakeCatalog(catalogModels),
            adapterFactory: (sel) => new SensitiveFakeAdapter(sel.modelId),
            profile: {
                id: "default",
                systemPrompt: "System prompt",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        await root1.controller.dispatch({
            kind: "create",
            intent: "Goal for restoration test",
        });

        await root1.controller.dispatch({ kind: "openModelSelector" });
        await root1.controller.dispatch({
            kind: "selectModel",
            model: catalogModels[1]!,
        });

        const goalId = root1.controller.getSnapshot().screen === "session"
            ? (root1.controller.getSnapshot() as any).goal.id
            : "";
        assert.ok(goalId.length > 0);

        // 2. 模拟新进程启动：当前环境 Provider 为 "openai"，兼容恢复
        const root2 = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: new SensitiveFakeAdapter("model-initial"),
            modelCatalog: new FakeCatalog(catalogModels),
            adapterFactory: (sel) => new SensitiveFakeAdapter(sel.modelId),
            profile: {
                id: "default",
                systemPrompt: "System prompt",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        // 恢复该 Goal
        await root2.controller.dispatch({
            kind: "selectGoal",
            goalId,
        });

        // 验证成功恢复且 Binding 正确重建为 model-custom
        const restoredView = root2.controller.getSnapshot();
        assert.equal(restoredView.screen, "session");
        assert.equal(restoredView.goal.state.modelSelection?.modelId, "model-custom");
        assert.equal(root2.modelBinding.current().selection.modelId, "model-custom");

        // 3. 模拟新进程启动，但当前环境配置为 Provider "anthropic"，存在冲突
        class AnthropicFakeAdapter implements LLMAdapter {
            readonly provider = "anthropic";
            readonly structuredOutputMode = "strict" as const;
            readonly calls: LLMRequest[] = [];
            async generate(request: LLMRequest): Promise<LLMResponse> {
                this.calls.push(request);
                return { content: "{}" };
            }
        }
        const anthropicAdapter = new AnthropicFakeAdapter();

        const root3 = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: anthropicAdapter,
            modelCatalog: new FakeCatalog([
                createDescriptor("claude-3-5", "Claude 3.5 Sonnet", "anthropic"),
            ]),
            adapterFactory: (sel) => new SensitiveFakeAdapter(sel.modelId),
            profile: {
                id: "default",
                systemPrompt: "System prompt",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        // 尝试恢复快照中 provider 为 "openai" 的 Goal
        await root3.controller.dispatch({
            kind: "selectGoal",
            goalId,
        });

        // 验证拦截：进入 model_select 错误态，未推进到 session，且未产生任何模型调用
        const conflictView = root3.controller.getSnapshot();
        assert.equal(conflictView.screen, "model_select");
        if (conflictView.screen === "model_select") {
            assert.equal(conflictView.state.status, "error");
            assert.match(
                conflictView.state.error.message,
                /provider/i,
            );
        }
        assert.equal(anthropicAdapter.calls.length, 0);
    } finally {
        await cleanup();
    }
});

test("非安全等待点拦截：非等待状态拒绝打开模型选择器，单 Controller 保持状态串行与稳定", async () => {
    const { workspace, cleanup } = await setupE2eWorkspace();
    try {
        const initialAdapter = new SensitiveFakeAdapter("model-alpha");
        const catalogModels = [createDescriptor("model-alpha", "Model Alpha")];

        const root = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: initialAdapter,
            modelCatalog: new FakeCatalog(catalogModels),
            adapterFactory: (sel) => new SensitiveFakeAdapter(sel.modelId),
            profile: {
                id: "default",
                systemPrompt: "System prompt",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        // 处于 goal_select 屏幕时，拒绝 openModelSelector
        await root.controller.dispatch({ kind: "resume" });
        assert.equal(root.controller.getSnapshot().screen, "goal_select");

        await root.controller.dispatch({ kind: "openModelSelector" });
        // 依然停在 goal_select 屏幕
        assert.equal(root.controller.getSnapshot().screen, "goal_select");
        assert.match(root.controller.getSnapshot().error?.message ?? "", /not allowed on the current screen/i);
    } finally {
        await cleanup();
    }
});

test("单 Controller 串行化防重入与非法 Slash 命令拦截", async () => {
    const { workspace, cleanup } = await setupE2eWorkspace();
    try {
        const catalogModels = [createDescriptor("model-alpha", "Model Alpha")];
        const initialAdapter = new SensitiveFakeAdapter("model-alpha");

        const root = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: initialAdapter,
            modelCatalog: new FakeCatalog(catalogModels),
            adapterFactory: (sel) => new SensitiveFakeAdapter(sel.modelId),
            profile: {
                id: "default",
                systemPrompt: "System prompt",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        // 1. 非法 Slash 命令拦截
        const registry = createSlashCommandRegistry<ModelCommandEffect>();
        registry.register(modelCommandDefinition);

        const invalidCommand = "/nonexistent-command foo bar";
        const dispatchResult = await registry.dispatch(invalidCommand);
        assert.equal(dispatchResult.kind, "rejected");
        assert.match(dispatchResult.message, /Unknown slash command/i);

        // 2. 正常创建 Goal
        await root.controller.dispatch({
            kind: "create",
            intent: "Regular goal creation",
        });
        assert.equal(root.controller.getSnapshot().screen, "session");

        // 3. 验证并发重入防护：正在执行命令时派发第二个命令被快速拒绝
        let slowAdapterResolve: (() => void) | undefined;
        const slowAdapterPromise = new Promise<void>((resolve) => {
            slowAdapterResolve = resolve;
        });

        class SlowAdapter implements LLMAdapter {
            readonly provider = "openai";
            readonly structuredOutputMode = "strict" as const;
            async generate(): Promise<LLMResponse> {
                await slowAdapterPromise;
                return {
                    content: JSON.stringify({
                        result: {
                            kind: "question",
                            question: "Next question",
                            memoryPatch: null,
                        },
                    }),
                };
            }
        }

        const slowAdapter = new SlowAdapter();
        const slowRoot = await createCompositionRoot({
            cwd: workspace,
            env: { LAZYGOAL_HOME: join(workspace, "lazygoal-home") },
            adapter: slowAdapter,
            modelCatalog: new FakeCatalog(catalogModels),
            profile: {
                id: "default",
                systemPrompt: "System prompt",
                instructions: [],
                toolIds: [],
            },
            toolPolicy: createDefaultToolPolicy(),
        });

        // 启动一个耗时的 dispatch
        const p1 = slowRoot.controller.dispatch({
            kind: "create",
            intent: "Long running task",
        });

        // 立即尝试第二次 dispatch
        await assert.rejects(
            slowRoot.controller.dispatch({
                kind: "create",
                intent: "Conflicting task",
            }),
            /Another UI command is already in progress/i,
        );

        // 释放第一次 dispatch
        slowAdapterResolve?.();
        await p1;
    } finally {
        await cleanup();
    }
});
