import { readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const REQUIRED_FIELDS = [
    "feature",
    "status",
    "summary",
    "source_spec",
    "distilled_at",
    "reviewed_at",
    "tags",
    "authorities",
];
const OPTIONAL_FIELDS = ["status_reason", "supersedes", "superseded_by"];
const ALLOWED_FIELDS = new Set([...REQUIRED_FIELDS, ...OPTIONAL_FIELDS]);
const ALLOWED_STATUSES = new Set([
    "active",
    "needs-review",
    "superseded",
    "obsolete",
]);
const REQUIRED_SECTIONS = [
    "Purpose",
    "Durable Decisions",
    "Guardrails",
    "Revisit When",
    "Sources",
];
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const SOURCE_PATTERN = /^- (S\d+): `([^`]+)`$/;
const DECISION_PATTERN = /^- (D\d+) — /;
const INDEX_HEADER = [
    "# Project Memory Index",
    "",
    "<!-- Generated by `npm run memory:index`; do not edit manually. -->",
    "",
    "| Memory | Summary | Tags | Status | Source Spec | Reviewed |",
    "|---|---|---|---|---|---|",
];

function fail(message) {
    throw new Error(message);
}

function parseValue(raw, field, capsulePath) {
    if (raw.startsWith("[") && raw.endsWith("]")) {
        const inner = raw.slice(1, -1).trim();
        if (inner === "") {
            return [];
        }
        return inner.split(",").map((item) => item.trim());
    }
    if (raw.startsWith('"')) {
        try {
            return JSON.parse(raw);
        } catch {
            fail(`${capsulePath}: ${field} 必须是合法的单行 JSON 字符串`);
        }
    }
    if (raw === "") {
        fail(`${capsulePath}: ${field} 不能为空`);
    }
    return raw;
}

export function parseCapsule(text, capsulePath) {
    const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
    if (match === null) {
        fail(`${capsulePath}: 缺少完整 frontmatter`);
    }

    const fields = {};
    for (const line of match[1].split("\n")) {
        const separator = line.indexOf(":");
        if (separator <= 0) {
            fail(`${capsulePath}: 无法解析 frontmatter 行 ${JSON.stringify(line)}`);
        }
        const key = line.slice(0, separator).trim();
        const raw = line.slice(separator + 1).trim();
        if (!ALLOWED_FIELDS.has(key)) {
            fail(`${capsulePath}: 不允许的 frontmatter 字段 ${key}`);
        }
        if (Object.hasOwn(fields, key)) {
            fail(`${capsulePath}: 重复的 frontmatter 字段 ${key}`);
        }
        fields[key] = parseValue(raw, key, capsulePath);
    }

    for (const field of REQUIRED_FIELDS) {
        if (!Object.hasOwn(fields, field)) {
            fail(`${capsulePath}: 缺少 frontmatter 字段 ${field}`);
        }
    }

    return { fields, body: match[2] };
}

function assertString(fields, field, capsulePath) {
    if (typeof fields[field] !== "string" || fields[field].trim() === "") {
        fail(`${capsulePath}: ${field} 必须是非空字符串`);
    }
}

function assertArray(fields, field, capsulePath, { nonEmpty = false } = {}) {
    const value = fields[field];
    if (!Array.isArray(value) || value.some((item) => item === "")) {
        fail(`${capsulePath}: ${field} 必须是单行 flow sequence`);
    }
    if (nonEmpty && value.length === 0) {
        fail(`${capsulePath}: ${field} 不能为空`);
    }
}

function assertRelativeProjectPath(value, field, capsulePath) {
    if (
        path.posix.isAbsolute(value)
        || value.includes("\\")
        || value.split("/").includes("..")
        || value.startsWith("./")
    ) {
        fail(`${capsulePath}: ${field} 必须是 project-root-relative POSIX 路径`);
    }
}

async function isRegularFile(target) {
    try {
        return (await stat(target)).isFile();
    } catch {
        return false;
    }
}

function sectionRanges(body, capsulePath) {
    const headings = [...body.matchAll(/^## (.+)$/gm)].map((match) => ({
        name: match[1],
        start: match.index,
        contentStart: match.index + match[0].length + 1,
    }));
    const names = headings.map(({ name }) => name);
    if (JSON.stringify(names) !== JSON.stringify(REQUIRED_SECTIONS)) {
        fail(`${capsulePath}: 二级章节必须严格为 ${REQUIRED_SECTIONS.join(" → ")}`);
    }
    return headings.map((heading, index) => ({
        name: heading.name,
        content: body.slice(
            heading.contentStart,
            headings[index + 1]?.start ?? body.length,
        ).trim(),
    }));
}

async function validateSources(sections, projectRoot, capsulePath) {
    const sources = new Map();
    const sourceSection = sections.find(({ name }) => name === "Sources");
    for (const line of sourceSection.content.split("\n").filter(Boolean)) {
        const match = SOURCE_PATTERN.exec(line);
        if (match === null) {
            fail(`${capsulePath}: Sources 只允许 - S<N>: \`path\` 格式`);
        }
        if (sources.has(match[1])) {
            fail(`${capsulePath}: 重复的来源 ${match[1]}`);
        }
        const [sourcePath] = match[2].split("#", 1);
        assertRelativeProjectPath(sourcePath, match[1], capsulePath);
        if (!await isRegularFile(path.join(projectRoot, sourcePath))) {
            fail(`${capsulePath}: 来源 ${match[1]} 不存在: ${sourcePath}`);
        }
        sources.set(match[1], match[2]);
    }
    if (sources.size === 0) {
        fail(`${capsulePath}: Sources 不能为空`);
    }

    const cited = new Set();
    for (const sectionName of ["Purpose", "Durable Decisions", "Guardrails"]) {
        const section = sections.find(({ name }) => name === sectionName);
        const claimLines = section.content.split("\n").filter((line) => line.startsWith("- "));
        if (claimLines.length === 0) {
            fail(`${capsulePath}: ${sectionName} 至少需要一条命题`);
        }
        for (const line of claimLines) {
            const citation = / \[((?:S\d+)(?:, S\d+)*)\]$/.exec(line);
            if (citation === null) {
                fail(`${capsulePath}: ${sectionName} 命题必须以来源 ID 结尾: ${line}`);
            }
            for (const id of citation[1].split(", ")) {
                if (!sources.has(id)) {
                    fail(`${capsulePath}: 引用了未定义来源 ${id}`);
                }
                cited.add(id);
            }
        }
    }
    for (const id of sources.keys()) {
        if (!cited.has(id)) {
            fail(`${capsulePath}: 来源 ${id} 未被任何命题引用`);
        }
    }
}

async function validateCapsule(projectRoot, capsulePath, text) {
    const relativePath = path.posix.join("project-memory/features", path.basename(capsulePath));
    const { fields, body } = parseCapsule(text, relativePath);
    for (const field of [
        "feature",
        "status",
        "summary",
        "source_spec",
        "distilled_at",
        "reviewed_at",
    ]) {
        assertString(fields, field, relativePath);
    }
    assertArray(fields, "tags", relativePath, { nonEmpty: true });
    assertArray(fields, "authorities", relativePath, { nonEmpty: true });

    const expectedFeature = path.basename(capsulePath, ".md");
    if (fields.feature !== expectedFeature) {
        fail(`${relativePath}: feature 必须与文件名一致`);
    }
    if (!ALLOWED_STATUSES.has(fields.status)) {
        fail(`${relativePath}: 非法 status ${fields.status}`);
    }
    if (fields.source_spec !== `specs/${fields.feature}/`) {
        fail(`${relativePath}: source_spec 必须与 feature 一致并以 / 结尾`);
    }
    if (!DATE_PATTERN.test(fields.distilled_at) || !DATE_PATTERN.test(fields.reviewed_at)) {
        fail(`${relativePath}: distilled_at 和 reviewed_at 必须是 YYYY-MM-DD`);
    }
    if (fields.reviewed_at < fields.distilled_at) {
        fail(`${relativePath}: reviewed_at 不能早于 distilled_at`);
    }
    if (!await isRegularFile(path.join(projectRoot, fields.source_spec, "requirements.md"))) {
        fail(`${relativePath}: source_spec 缺少 requirements.md`);
    }
    for (const authority of fields.authorities) {
        assertRelativeProjectPath(authority, "authorities", relativePath);
        if (!await isRegularFile(path.join(projectRoot, authority))) {
            fail(`${relativePath}: authority 不存在: ${authority}`);
        }
    }
    for (const relation of ["supersedes", "superseded_by"]) {
        if (Object.hasOwn(fields, relation)) {
            assertArray(fields, relation, relativePath, { nonEmpty: true });
            for (const target of fields[relation]) {
                assertRelativeProjectPath(target, relation, relativePath);
            }
        }
    }

    const hasReason = typeof fields.status_reason === "string"
        && fields.status_reason.trim() !== "";
    if (fields.status === "active") {
        if (Object.hasOwn(fields, "status_reason") || Object.hasOwn(fields, "superseded_by")) {
            fail(`${relativePath}: active 不得包含 status_reason 或 superseded_by`);
        }
    } else if (!hasReason) {
        fail(`${relativePath}: ${fields.status} 必须包含非空 status_reason`);
    }
    if (fields.status === "superseded" && !Object.hasOwn(fields, "superseded_by")) {
        fail(`${relativePath}: superseded 必须包含 superseded_by`);
    }
    if (fields.status !== "superseded" && Object.hasOwn(fields, "superseded_by")) {
        fail(`${relativePath}: 只有 superseded 可以包含 superseded_by`);
    }

    const sections = sectionRanges(body, relativePath);
    const decisions = sections.find(({ name }) => name === "Durable Decisions").content
        .split("\n")
        .filter((line) => line.startsWith("- "));
    const decisionIds = decisions.map((line) => DECISION_PATTERN.exec(line)?.[1]);
    if (decisionIds.some((id) => id === undefined)) {
        fail(`${relativePath}: Durable Decisions 必须使用 - D<N> — 格式`);
    }
    if (new Set(decisionIds).size !== decisionIds.length) {
        fail(`${relativePath}: Durable Decision ID 必须唯一`);
    }
    if (sections.find(({ name }) => name === "Revisit When").content === "") {
        fail(`${relativePath}: Revisit When 不能为空`);
    }
    await validateSources(sections, projectRoot, relativePath);
    return { relativePath, fields };
}

function escapeCell(value) {
    return value.replaceAll("|", "\\|");
}

export function renderIndex(capsules) {
    const rows = capsules
        .toSorted((left, right) => left.fields.feature.localeCompare(right.fields.feature))
        .map(({ relativePath, fields }) => {
            const fileName = path.posix.basename(relativePath);
            const memory = `[${relativePath}](./features/${fileName})`;
            const source = `[${fields.source_spec}](../${fields.source_spec})`;
            return `| ${memory} | ${escapeCell(fields.summary)} | ${fields.tags.join(", ")} | ${fields.status} | ${source} | ${fields.reviewed_at} |`;
        });
    return [...INDEX_HEADER, ...rows, ""].join("\n");
}

function validateRelations(capsules) {
    const byPath = new Map(capsules.map((capsule) => [capsule.relativePath, capsule]));
    for (const capsule of capsules) {
        for (const relation of ["supersedes", "superseded_by"]) {
            for (const targetPath of capsule.fields[relation] ?? []) {
                const target = byPath.get(targetPath);
                if (target === undefined) {
                    fail(`${capsule.relativePath}: ${relation} 目标不存在: ${targetPath}`);
                }
                const reciprocal = relation === "supersedes" ? "superseded_by" : "supersedes";
                if (!(target.fields[reciprocal] ?? []).includes(capsule.relativePath)) {
                    fail(`${capsule.relativePath}: ${relation} 与 ${targetPath} 不互惠`);
                }
            }
        }
    }

    const visiting = new Set();
    const visited = new Set();
    function visit(capsule) {
        if (visiting.has(capsule.relativePath)) {
            fail(`${capsule.relativePath}: superseded_by 存在循环`);
        }
        if (visited.has(capsule.relativePath)) {
            return;
        }
        visiting.add(capsule.relativePath);
        for (const target of capsule.fields.superseded_by ?? []) {
            visit(byPath.get(target));
        }
        visiting.delete(capsule.relativePath);
        visited.add(capsule.relativePath);
    }
    for (const capsule of capsules) {
        visit(capsule);
    }
}

async function coverageWarnings(projectRoot, capsules) {
    const specsRoot = path.join(projectRoot, "specs");
    const known = new Set(capsules.map(({ fields }) => fields.feature));
    const warnings = [];
    for (const entry of await readdir(specsRoot, { withFileTypes: true })) {
        if (!entry.isDirectory() || known.has(entry.name)) {
            continue;
        }
        const specRoot = path.join(specsRoot, entry.name);
        const required = ["requirements.md", "design.md", "tasks.md"];
        if (!(await Promise.all(required.map((name) => isRegularFile(path.join(specRoot, name))))).every(Boolean)) {
            continue;
        }
        const tasks = await readFile(path.join(specRoot, "tasks.md"), "utf8");
        const checkboxes = [...tasks.matchAll(/^\s*- \[([ xX])\] /gm)];
        if (checkboxes.length > 0 && checkboxes.every((match) => match[1].toLowerCase() === "x")) {
            warnings.push(`specs/${entry.name}/ 的 checkbox 已全部完成但尚无 Capsule；需要单独证据核验和明确 distillation 授权`);
        }
    }
    return warnings.toSorted();
}

export async function inspectProject(projectRoot) {
    const featureRoot = path.join(projectRoot, "project-memory", "features");
    const entries = (await readdir(featureRoot, { withFileTypes: true }))
        .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
        .toSorted((left, right) => left.name.localeCompare(right.name));
    const capsules = [];
    for (const entry of entries) {
        const capsulePath = path.join(featureRoot, entry.name);
        capsules.push(await validateCapsule(
            projectRoot,
            capsulePath,
            await readFile(capsulePath, "utf8"),
        ));
    }
    const features = capsules.map(({ fields }) => fields.feature);
    if (new Set(features).size !== features.length) {
        fail("存在重复 feature Capsule");
    }
    validateRelations(capsules);
    return {
        capsules,
        index: renderIndex(capsules),
        warnings: await coverageWarnings(projectRoot, capsules),
    };
}

export async function checkProject(projectRoot) {
    const inspection = await inspectProject(projectRoot);
    const indexPath = path.join(projectRoot, "project-memory", "index.md");
    const actual = await readFile(indexPath, "utf8");
    if (actual !== inspection.index) {
        fail("project-memory/index.md 与 Capsule 元数据不一致；运行 npm run memory:index");
    }
    return inspection;
}

export async function writeIndex(projectRoot) {
    const inspection = await inspectProject(projectRoot);
    const indexPath = path.join(projectRoot, "project-memory", "index.md");
    const temporaryPath = `${indexPath}.tmp-${process.pid}`;
    try {
        await writeFile(temporaryPath, inspection.index, "utf8");
        await rename(temporaryPath, indexPath);
    } catch (error) {
        await unlink(temporaryPath).catch(() => undefined);
        throw error;
    }
    return inspection;
}

async function main() {
    const command = process.argv[2];
    const projectRoot = path.resolve(process.argv[3] ?? process.cwd());
    const result = command === "check"
        ? await checkProject(projectRoot)
        : command === "write-index"
            ? await writeIndex(projectRoot)
            : fail("usage: node scripts/project-memory.mjs <check|write-index> [project-root]");
    for (const warning of result.warnings) {
        process.stderr.write(`warning: ${warning}\n`);
    }
    process.stdout.write(`Project Memory 验证通过：${result.capsules.length} 个 Capsule\n`);
}

const invokedPath = process.argv[1] === undefined ? undefined : pathToFileURL(process.argv[1]).href;
if (invokedPath === import.meta.url) {
    main().catch((error) => {
        process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
        process.exitCode = 1;
    });
}
